//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVC_with_Ajax_JsonResult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILDREN_DETAILS
    {
        public System.Guid CHILDREN_ID { get; set; }
        public Nullable<System.Guid> USER_ID { get; set; }
        public string CHILDREN_NAME { get; set; }
        public Nullable<System.DateTime> CHILD_DOB { get; set; }
        public string CHILDREN_GENDER { get; set; }
        public Nullable<System.Guid> CREATED_BY_ID { get; set; }
        public Nullable<System.DateTime> CREATED_BY_DT { get; set; }
        public Nullable<System.Guid> MODIFIED_BY_ID { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
    }
}
